### ISSUE TITLE
There are no "RESOURCES" and "WORKSPACE" labels in the AZURE view

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureresourcegroups#595]
**Environment:** VSCode.dev
**Regression:** Not a regression

**Repro Steps:**

1. Install the Resource Group extension.
2. Navigate to AZURE view.
3. Check the AZURE view.

**Expect:**
There are "RESOURCES" and "WORKSPACE" labels in the AZURE view.
![image](https://user-images.githubusercontent.com/107091828/221487506-c6851b1f-6f61-4c99-9fb6-5c8339f76fa7.png)

**Actual:**
There are no "RESOURCES" and "WORKSPACE" labels in the AZURE view.
![image](https://user-images.githubusercontent.com/107091828/221487463-ea20e8c2-e244-43b0-a79d-53d27048a1bb.png)

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/607

**Comment by v-chenzha** [comment]
@nturinski  This issue still reproduces on Resource Groups extension testing for vscode.dev, reopen it.
![image](https://user-images.githubusercontent.com/107091828/227825335-5b4f6c71-90ec-4313-9743-88d8994f5044.png)
![image](https://user-images.githubusercontent.com/107091828/227825397-f0aa494e-5c24-4e90-956a-c63d51c68608.png)
